In [1]:
import numpy as np
import pandas as pd

import os

from helpers.table_processing import preprocess_table


EXCEL_DIR = 'datasets/'
DATASETS = os.listdir(EXCEL_DIR)

## Example 1

- Dataset for https://www.ons.gov.uk/peoplepopulationandcommunity/healthandsocialcare/causesofdeath/bulletins/alcoholrelateddeathsintheunitedkingdom/latest


- Some sheets work beautifully. Specifically those with actually useful data.
- Others, where data specification and other meta-information is suppplied -- not so much

In [16]:
table_data = pd.ExcelFile('datasets/peoplepopulationandcommunity_healthandsocialcare_causesofdeath_datasets_alcoholspecificdeathsintheukmaindataset.xls')

sheet_names = table_data.sheet_names
df = table_data.parse(sheet_names[3])

/Users/pafitis/miniforge3/envs/comp0087/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:312: UserWarning: Slicer List extension is not supported and will be removed
  warn(msg)

In [17]:
df

,Back to contents,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14
0,Table 1: Alcohol-specific age-standardised dea...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Please choose one option (highlighted in blue)...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Sex,NaN,Geography,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,NaN,NaN,Values,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,Year of registration,Number of deaths,"Age-standardised rate per 100,000",Lower 95% confidence interval,Upper 95% confidence interval,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,2019,7565,11.8,11.6,12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,NaN,2018,7551,11.9,11.6,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,2017,7697,12.2,12,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,2016,7327,11.7,11.5,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,2015,7006,11.3,11.1,11.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,2014,7002,11.4,11.2,11.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,NaN,2013,6791,11.2,10.9,11.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,NaN,2012,6669,11.1,10.8,11.4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,2011,7179,12,11.8,12.3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,2010,7069,12,11.7,12.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,2009,6910,11.8,11.5,12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,NaN,2008,7347,12.7,12.5,13,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,2007,6960,12.2,11.9,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,2006,6938,12.3,12,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,2005,6622,11.8,11.6,12.1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,NaN,2004,6386,11.5,11.3,11.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,NaN,2003,6255,11.4,11.1,11.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,NaN,2002,5915,10.9,10.6,11.2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,NaN,2001,5701,10.6,10.3,10.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,"Source: Office for National Statistics, Nation...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Footnotes:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,1 Age-standardised mortality rates are present...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,2 The lower and upper 95% confidence limits ha...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,3 Cause of death was defined using the Interna...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,"4 Figures for the United Kingdom, England and ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,5 Figures are based on the date of registratio...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,6 The underlying data used in this table can b...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
preprocess_table(df)

,NaN,Year of registration,Number of deaths,"Age-standardised rate per 100,000",Lower 95% confidence interval,Upper 95% confidence interval
12,-,2019,7565,11.8,11.6,12.1
13,-,2018,7551,11.9,11.6,12.2
14,-,2017,7697,12.2,12.0,12.5
15,-,2016,7327,11.7,11.5,12.0
16,-,2015,7006,11.3,11.1,11.6
17,-,2014,7002,11.4,11.2,11.7
18,-,2013,6791,11.2,10.9,11.5
19,-,2012,6669,11.1,10.8,11.4
20,-,2011,7179,12.0,11.8,12.3
21,-,2010,7069,12.0,11.7,12.2
22,-,2009,6910,11.8,11.5,12.1
23,-,2008,7347,12.7,12.5,13.0
24,-,2007,6960,12.2,11.9,12.5
25,-,2006,6938,12.3,12.0,12.5
26,-,2005,6622,11.8,11.6,12.1
27,-,2004,6386,11.5,11.3,11.8
28,-,2003,6255,11.4,11.1,11.7
29,-,2002,5915,10.9,10.6,11.2
30,-,2001,5701,10.6,10.3,10.8

1. Greatly reduced sized to the _useful_ section
2. Still some artifacts, such as the first column
    - entries "-" are not considered as empty
    - possibly should handle this
3. Largely clean

## Example 1 (cont.)

- I took some design choices
- I forward fill some columns to fix multiple level header-columns but this fails sometimes
- I also replace NANs to "-" to match ONS data but I think I'll remove this
- I do not currently remove columns that are mostly NAN as I thought they would still have valuable info -- maybe this should be implemented. (I currently remove rows that are mostly NAN >90% empty)

In [19]:
df = table_data.parse(sheet_names[1])
df

,Back to contents,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,Alcohol-specific deaths in the UK: registered ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,Copyright and reproduction,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,© Crown copyright 2021,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
59,NaN,"We would welcome feedback on the content, form...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
60,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
61,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,NaN,National Records of Scotland,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
63,NaN,Northern Ireland Statistics and Research Agency,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
preprocess_table(df)

,Alcohol-specific deaths in the UK: registered in 2019,NaN,NaN,NaN,NaN
3,Copyright and reproduction,-,-,-,-
4,© Crown copyright 2021,-,-,-,-
5,You may re-use this information (not including...,-,-,-,-
7,www.nationalarchives.gov.uk/doc/open-governmen...,-,-,-,-
8,This document/publication is also available on...,-,-,-,www.ons.gov.uk
9,Where we have identified any third party copyr...,-,-,-,www.ons.gov.uk
12,Any enquiries regarding this document/publicat...,-,-,-,www.ons.gov.uk
13,"Information Policy Team, The National Archives...",-,-,-,www.ons.gov.uk
14,Email:,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
16,Contact details,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
18,"Life Style and Risk Factors Team, Health Analy...",psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
19,Office for National Statistics,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
20,Government Buildings,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
21,Cardiff Road,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
22,Newport,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
23,Gwent NP10 8XG,psi@nationalarchives.gov.uk,-,-,www.ons.gov.uk
25,Tel: 01633 651004,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
27,"In addition to the tables published, bespoke a...",psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
33,Links to further information,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
35,Alcohol-specific deaths in the UK,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
36,Deaths in the UK that are known to be direct c...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
38,Alcohol-specific deaths in the UK QMI,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
39,Quality and Methodology Information (QMI) repo...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
42,ONS charging rates for bespoke analysis,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
43,The ONS charging policy provides clarification...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
46,Deaths registered in England and Wales,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
47,This annual release provides death registratio...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
50,Mortality statistics in England and Wales QMI,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
51,Quality and Methodology Information (QMI) repo...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
54,User guide to mortality statistics,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
55,The user guide to mortality statistics provide...,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
58,Feedback,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
59,"We would welcome feedback on the content, form...",psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
62,National Records of Scotland,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk
63,Northern Ireland Statistics and Research Agency,psi@nationalarchives.gov.uk,E-mail:,health.data@ons.gov.uk,www.ons.gov.uk

In [31]:
table_data = pd.ExcelFile(EXCEL_DIR + DATASETS[402])
sheet_names = table_data.sheet_names
df = table_data.parse(sheet_names[3])

In [36]:
df

,Measuring National Well-being - Assessments of change,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Data are the latest available at 15th October ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Broadly speaking, indicators have only been as...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...
70,4. This measure is calculated using multiple y...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,5. This measure is taken from an administrativ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,6. Change for this measure is based on progres...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,7. Change for this measure is based on progres...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,8. Change for this measure is based on progres...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

- See here that forward fill of columns fails
- This is because I use df.shape[0] * 0.9 as a threshold to beat for filling
- All these thresholds are very subjective

In [33]:
preprocess_table(df)

,Personal well-being,1.1,Very high rating of satisfaction with their lives overall2,Method of assessment,Short-term1,Long-term1,NaN,I,Improved
13,Personal well-being,1.1,Very high rating of satisfaction with their li...,Confidence intervals,I,I,-,I,Improved
14,-,1.2,Very high rating of how worthwhile they feel t...,Confidence intervals,NC,I,-,NC,No overall change
15,-,1.3,Rated their happiness yesterday as very high2,Confidence intervals,NC,I,-,NC,Not assessed
16,-,1.4,Rated their anxiety yesterday as very low2,Confidence intervals,NC,I,-,D,Deteriorated
17,-,1.5,Population mental well-being3,Confidence intervals,I,NC,-,D,Deteriorated
19,Our relationships,2.1,Proportion of those in fairly or extremely unh...,Confidence intervals,I,I,-,D,Deteriorated
20,-,2.2,Feelings of loneliness often/always,Confidence intervals,NC,NC,-,D,Deteriorated
21,-,2.3,"Has a spouse, family member or friend to rely ...",Confidence intervals,-,D,-,D,Deteriorated
23,Health,3.1,Healthy life expectancy at birth (male)4,Confidence intervals,NC,NC,-,D,Deteriorated
24,-,3.1,Healthy life expectancy at birth (female)4,Confidence intervals,NC,NC,-,D,Deteriorated
25,-,3.2,Percentage who reported a disability,Not assessed,-,-,-,D,Deteriorated
26,-,3.3,Mostly or completely satisfied with their health,Confidence intervals,NC,I,-,D,Deteriorated
27,-,3.4,Some evidence indicating depression or anxiety,Confidence intervals,D,NC,-,D,Deteriorated
29,What we do,4.1,Unemployment rate2,Confidence intervals,NC,I,-,D,Deteriorated
30,-,4.2,Mostly or completely satisfied with their job,Confidence intervals,NC,I,-,D,Deteriorated
31,-,4.3,Mostly or completely satisfied with their amou...,Confidence intervals,NC,I,-,D,Deteriorated
32,-,4.4,Volunteered more than once in the last 12 months,Confidence intervals,D,NC,-,D,Deteriorated
33,-,4.5,Engaged with/participated in arts or cultural ...,Confidence intervals,NC,D,-,D,Deteriorated
34,-,4.6,Adult participation in 30 mins of moderate int...,Confidence intervals,I,-,-,D,Deteriorated
36,Where we live,5.1,"Crimes against the person (per 1,000 adults)",Confidence intervals,NC,I,-,D,Deteriorated
37,-,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,NC,I,-,D,Deteriorated
38,-,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,I,I,-,D,Deteriorated
39,-,5.3,Accessed natural environment at least once a w...,Confidence intervals,NC,I,-,D,Deteriorated
40,-,5.4,Agreed/agreed strongly they felt they belonged...,Confidence intervals,-,I,-,D,Deteriorated
41,-,5.5,Average minimum travel time to nearest key ser...,Not assessed,-,-,-,D,Deteriorated
42,-,5.6,Fairly/very satisfied with their accommodation,Confidence intervals,NC,NC,-,D,Deteriorated
44,Personal finance,6.1,Individuals in households with less than 60% o...,Confidence intervals,NC,NC,-,D,Deteriorated
45,-,6.2,"Median wealth per household, including pension...",Expert opinion,-,I,,D,Deteriorated
46,-,6.3,Real median household income,Expert opinion,NC,I,,D,Deteriorated
47,-,6.4,Mostly or completely satisfied with the income...,Confidence intervals,NC,I,,D,Deteriorated
48,-,6.5,Report finding it quite or very difficult to g...,Confidence intervals,NC,I,,D,Deteriorated
50,The economy,7.1,Real net national disposable income per head,Expert opinion,I,I,,D,Deteriorated
51,-,7.2,UK public sector net debt as a percentage of G...,Not assessed,-,-,,D,Deteriorated
52,-,7.3,Inflation rate (as measured by CPIH),Not assessed,-,-,,D,Deteriorated
54,Education and skills,8.1,Human capital - the value of individuals' skil...,Expert opinion,D,I,,D,Deteriorated
55,-,8.2,"Those Not in Education, Employment or Training...",Confidence intervals,NC,I,,D,Deteriorated
56,-,8.3,UK residents aged 16 to 64 with no qualifications,Confidence intervals,NC,I,,D,Deteriorated
58,Governance,9.1,Voter turnout (at UK General Elections)5,Increase/decrease,I,I,,D,Deteriorated
59,-,9.2,Those who have trust in national Government,Confidence intervals,D,D,,D,Deteriorated
61,The natural environment,10.1,Total green house gas emissions (millions of t...,Progress towards target,I,I,,D,Deteriorated
62,-,10.2,Protected areas in the UK (Millions hectares)5,Expert opinion,I,I,,D,Deteriorated
63,-,10.3,Energy consumed within the UK from renewable s...,Progress towards target,I,I,,D,Deteriorated
64,-,10.4,Waste from households that is recycled8,Progress towards target,NC,NC,,D,Deteriorated

## Example 2

In [42]:
table_data = pd.ExcelFile('datasets/businessindustryandtrade_itandinternetindustry_datasets_ictactivityofukbusinessesecommerceandictactivity.xls')
sheet_names = table_data.sheet_names
df = table_data.parse(sheet_names[2])

In [43]:
df

,"Table 2: UK e-commerce sales, by size of business, 2009 to 2019",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,£ billion,NaN
1,NaN,NaN,0 to 9 employees,10 to 49 employees,50 to 249 employees,250 to 999 employees,1000 or more employees,10 or more employees,All businesses,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Website sales,2009.0,-,7.8,11.4,31.5,59.9,110.6,-,NaN
4,NaN,2010.0,-,10.2,12.8,31.2,64.3,118.5,-,NaN
5,NaN,2011.0,-,12.4,17.3,33.8,84.3,147.8,-,NaN
6,NaN,2012.0,-,18.4,17.6,40.1,96.7,172.9,-,NaN
7,NaN,2013.0,-,18.7,19.9,49.5,109.9,198,-,NaN
8,NaN,2014.0,17.1,20.7,21.7,40.4,127.6,210.4,227.4,NaN
9,NaN,2015.0,18.5,21.7,29.1,36.9,130.4,218.1,236.6,NaN
10,NaN,2016.0,17.5,26.4,28.3,34.7,141.1,230.4,247.9,NaN
11,NaN,2017.0,21.3,33.1,41.3,40.4,160.6,275.4,296.7,NaN
12,NaN,2018.0,32.1,42.5,50.9,52.6,176.3,322.3,354.4,NaN
13,NaN,2019.0,21.5,35.6,47.8,55.3,196.2,334.9,356.4,NaN
14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,EDI sales,2009.0,-,6.4,31.2,105.8,121,264.5,-,NaN
16,NaN,2010.0,-,8.6,31.4,127.9,132.5,300.5,-,NaN
17,NaN,2011.0,-,10.7,34,149.8,146.8,341.2,-,NaN
18,NaN,2012.0,-,9.1,37.9,117.6,136.2,300.7,-,NaN
19,NaN,2013.0,-,10.5,33.9,163.3,139.1,346.8,-,NaN
20,NaN,2014.0,2,8.7,29.3,117.7,128.4,284.1,286.1,NaN
21,NaN,2015.0,2.3,9.5,32.9,79.7,135.2,257.2,259.6,NaN
22,NaN,2016.0,5.9,10.2,36.4,73.2,135.2,255,260.9,NaN
23,NaN,2017.0,5.6,13.9,42,87.1,136.9,279.9,285.5,NaN
24,NaN,2018.0,6.1,13.9,48.8,101.3,153.3,317.3,323.4,NaN
25,NaN,2019.0,2.6,14.4,47,100.3,172.2,334,336.6,NaN
26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Total e-commerce sales,2009.0,-,14.2,42.6,137.4,180.9,375.1,-,NaN
28,NaN,2010.0,-,18.8,44.3,159.1,196.9,419,-,NaN
29,NaN,2011.0,-,23.1,51.3,183.6,231.1,489,-,NaN
30,NaN,2012.0,-,27.5,55.5,157.7,232.9,473.6,-,NaN
31,NaN,2013.0,-,29.1,53.8,212.9,249,544.7,-,NaN
32,NaN,2014.0,19,29.4,51,158.1,256,494.5,513.5,NaN
33,NaN,2015.0,20.8,31.2,62,116.6,265.6,475.4,496.2,NaN
34,NaN,2016.0,23.4,36.6,64.7,107.9,276.3,485.4,508.8,NaN
35,NaN,2017.0,27,47,83.3,127.5,297.5,555.2,582.2,NaN
36,NaN,2018.0,38.2,56.5,99.7,153.9,329.6,639.7,677.8,NaN
37,NaN,2019.0,24.1,50,94.8,155.6,368.5,668.9,693,NaN
38,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Source: Office for National Statistics,NaN
40,Coverage of micro-enterprises (those with less...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Cecil Prescott,NaN
41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,+44 (0)1633 456767,NaN
42,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ecommerce@ons.gov.uk,NaN
43,- denotes figures unavailable.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Estimates from 2017 onwards have been revised ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Publication date: 5 Feb 2021,NaN
45,Differences may occur between totals and the s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
preprocess_table(df)

,Website sales,2009.0,0 to 9 employees,10 to 49 employees,50 to 249 employees,250 to 999 employees,1000 or more employees,10 or more employees,All businesses
3,Website sales,2009.0,-,7.8,11.4,31.5,59.9,110.6,-
4,Website sales,2010.0,-,10.2,12.8,31.2,64.3,118.5,-
5,Website sales,2011.0,-,12.4,17.3,33.8,84.3,147.8,-
6,Website sales,2012.0,-,18.4,17.6,40.1,96.7,172.9,-
7,Website sales,2013.0,-,18.7,19.9,49.5,109.9,198.0,-
8,Website sales,2014.0,17.1,20.7,21.7,40.4,127.6,210.4,227.4
9,Website sales,2015.0,18.5,21.7,29.1,36.9,130.4,218.1,236.6
10,Website sales,2016.0,17.5,26.4,28.3,34.7,141.1,230.4,247.9
11,Website sales,2017.0,21.3,33.1,41.3,40.4,160.6,275.4,296.7
12,Website sales,2018.0,32.1,42.5,50.9,52.6,176.3,322.3,354.4
13,Website sales,2019.0,21.5,35.6,47.8,55.3,196.2,334.9,356.4
15,EDI sales,2009.0,-,6.4,31.2,105.8,121.0,264.5,-
16,EDI sales,2010.0,-,8.6,31.4,127.9,132.5,300.5,-
17,EDI sales,2011.0,-,10.7,34.0,149.8,146.8,341.2,-
18,EDI sales,2012.0,-,9.1,37.9,117.6,136.2,300.7,-
19,EDI sales,2013.0,-,10.5,33.9,163.3,139.1,346.8,-
20,EDI sales,2014.0,2,8.7,29.3,117.7,128.4,284.1,286.1
21,EDI sales,2015.0,2.3,9.5,32.9,79.7,135.2,257.2,259.6
22,EDI sales,2016.0,5.9,10.2,36.4,73.2,135.2,255.0,260.9
23,EDI sales,2017.0,5.6,13.9,42.0,87.1,136.9,279.9,285.5
24,EDI sales,2018.0,6.1,13.9,48.8,101.3,153.3,317.3,323.4
25,EDI sales,2019.0,2.6,14.4,47.0,100.3,172.2,334.0,336.6
27,Total e-commerce sales,2009.0,-,14.2,42.6,137.4,180.9,375.1,-
28,Total e-commerce sales,2010.0,-,18.8,44.3,159.1,196.9,419.0,-
29,Total e-commerce sales,2011.0,-,23.1,51.3,183.6,231.1,489.0,-
30,Total e-commerce sales,2012.0,-,27.5,55.5,157.7,232.9,473.6,-
31,Total e-commerce sales,2013.0,-,29.1,53.8,212.9,249.0,544.7,-
32,Total e-commerce sales,2014.0,19,29.4,51.0,158.1,256.0,494.5,513.5
33,Total e-commerce sales,2015.0,20.8,31.2,62.0,116.6,265.6,475.4,496.2
34,Total e-commerce sales,2016.0,23.4,36.6,64.7,107.9,276.3,485.4,508.8
35,Total e-commerce sales,2017.0,27,47.0,83.3,127.5,297.5,555.2,582.2
36,Total e-commerce sales,2018.0,38.2,56.5,99.7,153.9,329.6,639.7,677.8
37,Total e-commerce sales,2019.0,24.1,50.0,94.8,155.6,368.5,668.9,693

## Table Linearization

In [1]:
from helpers.table_processing import linearize_table, preprocess_table
import pandas as pd

# from helpers.configs import ROW_NAN_THRESHOLD, IMPUTE_COL_NANS, IMPUTE_COL_THRESHOLD, DROP_UNNAMED, FILL_NA, BACKFILL_HEADERS

In [2]:
filepath = 'datasets/peoplepopulationandcommunity_wellbeing_datasets_measuringnationalwellbeingdomainsandmeasures.xls'
    
table_data = pd.ExcelFile(filepath)
sheet_names = table_data.sheet_names

df = table_data.parse(sheet_names[3])
processed = preprocess_table(df)

# test linearizer
# data = {'Actors': ["Brad Pitt", "Leonardo Di Caprio", "George Clooney"],
#     'Age': ["56", "45", "59"],
#     'Number of movies': ["87", "53", "69"]
# }
# table = pd.DataFrame.from_dict(data)
linear_table = linearize_table(processed)

IMPUTE_COL_NANS: True
DROP_UNNAMED: True
BACKFILL_HEADERS: True
FILL_NA: True
IMPUTE_FIRST_COL_EMPTY: True
IMPUTE_COL_NANS: True
DROP_UNNAMED: True
BACKFILL_HEADERS: True
FILL_NA: True
IMPUTE_FIRST_COL_EMPTY: True

In [3]:
processed

,Personal well-being,1.1,Very high rating of satisfaction with their lives overall2,Method of assessment,Short-term1,Long-term1,-,I,Improved
0,Personal well-being,1.1,Very high rating of satisfaction with their li...,Confidence intervals,I,I,,I,Improved
1,Personal well-being,1.2,Very high rating of how worthwhile they feel t...,Confidence intervals,NC,I,,NC,No overall change
2,Personal well-being,1.3,Rated their happiness yesterday as very high2,Confidence intervals,NC,I,,NC,Not assessed
3,Personal well-being,1.4,Rated their anxiety yesterday as very low2,Confidence intervals,NC,I,,D,Deteriorated
4,Personal well-being,1.5,Population mental well-being3,Confidence intervals,I,NC,,D,Deteriorated
5,Our relationships,2.1,Proportion of those in fairly or extremely unh...,Confidence intervals,I,I,,D,Deteriorated
6,Our relationships,2.2,Feelings of loneliness often/always,Confidence intervals,NC,NC,,D,Deteriorated
7,Our relationships,2.3,"Has a spouse, family member or friend to rely ...",Confidence intervals,,D,,D,Deteriorated
8,Health,3.1,Healthy life expectancy at birth (male)4,Confidence intervals,NC,NC,,D,Deteriorated
9,Health,3.1,Healthy life expectancy at birth (female)4,Confidence intervals,NC,NC,,D,Deteriorated
10,Health,3.2,Percentage who reported a disability,Not assessed,,,,D,Deteriorated
11,Health,3.3,Mostly or completely satisfied with their health,Confidence intervals,NC,I,,D,Deteriorated
12,Health,3.4,Some evidence indicating depression or anxiety,Confidence intervals,D,NC,,D,Deteriorated
13,What we do,4.1,Unemployment rate2,Confidence intervals,NC,I,,D,Deteriorated
14,What we do,4.2,Mostly or completely satisfied with their job,Confidence intervals,NC,I,,D,Deteriorated
15,What we do,4.3,Mostly or completely satisfied with their amou...,Confidence intervals,NC,I,,D,Deteriorated
16,What we do,4.4,Volunteered more than once in the last 12 months,Confidence intervals,D,NC,,D,Deteriorated
17,What we do,4.5,Engaged with/participated in arts or cultural ...,Confidence intervals,NC,D,,D,Deteriorated
18,What we do,4.6,Adult participation in 30 mins of moderate int...,Confidence intervals,I,,,D,Deteriorated
19,Where we live,5.1,"Crimes against the person (per 1,000 adults)",Confidence intervals,NC,I,,D,Deteriorated
20,Where we live,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,NC,I,,D,Deteriorated
21,Where we live,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,I,I,,D,Deteriorated
22,Where we live,5.3,Accessed natural environment at least once a w...,Confidence intervals,NC,I,,D,Deteriorated
23,Where we live,5.4,Agreed/agreed strongly they felt they belonged...,Confidence intervals,,I,,D,Deteriorated
24,Where we live,5.5,Average minimum travel time to nearest key ser...,Not assessed,,,,D,Deteriorated
25,Where we live,5.6,Fairly/very satisfied with their accommodation,Confidence intervals,NC,NC,,D,Deteriorated
26,Personal finance,6.1,Individuals in households with less than 60% o...,Confidence intervals,NC,NC,,D,Deteriorated
27,Personal finance,6.2,"Median wealth per household, including pension...",Expert opinion,,I,,D,Deteriorated
28,Personal finance,6.3,Real median household income,Expert opinion,NC,I,,D,Deteriorated
29,Personal finance,6.4,Mostly or completely satisfied with the income...,Confidence intervals,NC,I,,D,Deteriorated
30,Personal finance,6.5,Report finding it quite or very difficult to g...,Confidence intervals,NC,I,,D,Deteriorated
31,The economy,7.1,Real net national disposable income per head,Expert opinion,I,I,,D,Deteriorated
32,The economy,7.2,UK public sector net debt as a percentage of G...,Not assessed,,,,D,Deteriorated
33,The economy,7.3,Inflation rate (as measured by CPIH),Not assessed,,,,D,Deteriorated
34,Education and skills,8.1,Human capital - the value of individuals' skil...,Expert opinion,D,I,,D,Deteriorated
35,Education and skills,8.2,"Those Not in Education, Employment or Training...",Confidence intervals,NC,I,,D,Deteriorated
36,Education and skills,8.3,UK residents aged 16 to 64 with no qualifications,Confidence intervals,NC,I,,D,Deteriorated
37,Governance,9.1,Voter turnout (at UK General Elections)5,Increase/decrease,I,I,,D,Deteriorated
38,Governance,9.2,Those who have trust in national Government,Confidence intervals,D,D,,D,Deteriorated
39,The natural environment,10.1,Total green house gas emissions (millions of t...,Progress towards target,I,I,,D,Deteriorated
40,The natural environment,10.2,Protected areas in the UK (Millions hectares)5,Expert opinion,I,I,,D,Deteriorated
41,The natural environment,10.3,Energy consumed within the UK from renewable s...,Progress towards target,I,I,,D,Deteriorated
42,The natural environment,10.4,Waste from households that is recycled8,Progress towards target,NC,NC,,D,Deteriorated

In [7]:
df[:50]

,Measuring National Well-being - Assessments of change,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8
0,Data are the latest available at 15th October ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,"Broadly speaking, indicators have only been as...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Confidence intervals give a measure of the sta...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Short-term changes are for 1 year (unless othe...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Some indicators have not been assessed. This c...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,NaN,NaN,NaN,Method of assessment,Short-term1,Long-term1,NaN,NaN,NaN
13,Personal well-being,1.1,Very high rating of satisfaction with their li...,Confidence intervals,I,I,NaN,I,Improved
14,NaN,1.2,Very high rating of how worthwhile they feel t...,Confidence intervals,NC,I,NaN,NC,No overall change
15,NaN,1.3,Rated their happiness yesterday as very high2,Confidence intervals,NC,I,NaN,NaN,Not assessed
16,NaN,1.4,Rated their anxiety yesterday as very low2,Confidence intervals,NC,I,NaN,D,Deteriorated
17,NaN,1.5,Population mental well-being3,Confidence intervals,I,NC,NaN,NaN,NaN
18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Our relationships,2.1,Proportion of those in fairly or extremely unh...,Confidence intervals,I,I,NaN,NaN,NaN
20,NaN,2.2,Feelings of loneliness often/always,Confidence intervals,NC,NC,NaN,NaN,NaN
21,NaN,2.3,"Has a spouse, family member or friend to rely ...",Confidence intervals,NaN,D,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Health,3.1,Healthy life expectancy at birth (male)4,Confidence intervals,NC,NC,NaN,NaN,NaN
24,NaN,3.1,Healthy life expectancy at birth (female)4,Confidence intervals,NC,NC,NaN,NaN,NaN
25,NaN,3.2,Percentage who reported a disability,Not assessed,NaN,NaN,NaN,NaN,NaN
26,NaN,3.3,Mostly or completely satisfied with their health,Confidence intervals,NC,I,NaN,NaN,NaN
27,NaN,3.4,Some evidence indicating depression or anxiety,Confidence intervals,D,NC,NaN,NaN,NaN
28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,What we do,4.1,Unemployment rate2,Confidence intervals,NC,I,NaN,NaN,NaN
30,NaN,4.2,Mostly or completely satisfied with their job,Confidence intervals,NC,I,NaN,NaN,NaN
31,NaN,4.3,Mostly or completely satisfied with their amou...,Confidence intervals,NC,I,NaN,NaN,NaN
32,NaN,4.4,Volunteered more than once in the last 12 months,Confidence intervals,D,NC,NaN,NaN,NaN
33,NaN,4.5,Engaged with/participated in arts or cultural ...,Confidence intervals,NC,D,NaN,NaN,NaN
34,NaN,4.6,Adult participation in 30 mins of moderate int...,Confidence intervals,I,NaN,NaN,NaN,NaN
35,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Where we live,5.1,"Crimes against the person (per 1,000 adults)",Confidence intervals,NC,I,NaN,NaN,NaN
37,NaN,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,NC,I,NaN,NaN,NaN
38,NaN,5.2,Felt fairly/very safe walking alone after dark...,Confidence intervals,I,I,NaN,NaN,NaN
39,NaN,5.3,Accessed natural environment at least once a w...,Confidence intervals,NC,I,NaN,NaN,NaN
40,NaN,5.4,Agreed/agreed strongly they felt they belonged...,Confidence intervals,NaN,I,NaN,NaN,NaN
41,NaN,5.5,Average minimum travel time to nearest key ser...,Not assessed,NaN,NaN,NaN,NaN,NaN
42,NaN,5.6,Fairly/very satisfied with their accommodation,Confidence intervals,NC,NC,NaN,NaN,NaN
43,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Personal finance,6.1,Individuals in households with less than 60% o...,Confidence intervals,NC,NC,NaN,NaN,NaN
45,NaN,6.2,"Median wealth per household, including pension...",Expert opinion,NaN,I,,NaN,NaN
46,NaN,6.3,Real median household income,Expert opinion,NC,I,NaN,NaN,NaN
47,NaN,6.4,Mostly or completely satisfied with the income...,Confidence intervals,NC,I,NaN,NaN,NaN
48,NaN,6.5,Report finding it quite or very difficult to g...,Confidence intervals,NC,I,NaN,NaN,NaN
49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN